/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author FJFF
 */
public class average extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(average.class.getName());

    /**
     * Creates new form average
     */
    public average() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        averagepanel = new javax.swing.JPanel();
        labelgrade1 = new javax.swing.JLabel();
        labelgrade2 = new javax.swing.JLabel();
        labelgrade3 = new javax.swing.JLabel();
        labelaverage = new javax.swing.JLabel();
        labelstate = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        txtgrade1 = new javax.swing.JTextField();
        txtgrade2 = new javax.swing.JTextField();
        txtgrade3 = new javax.swing.JTextField();
        txtaverage = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnbackavg = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        averagepanel.setBackground(new java.awt.Color(0, 51, 153));

        labelgrade1.setBackground(new java.awt.Color(255, 255, 255));
        labelgrade1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelgrade1.setForeground(new java.awt.Color(255, 255, 255));
        labelgrade1.setText("NOTA 1 :");

        labelgrade2.setBackground(new java.awt.Color(255, 255, 255));
        labelgrade2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelgrade2.setForeground(new java.awt.Color(255, 255, 255));
        labelgrade2.setText("NOTA 2 :");

        labelgrade3.setBackground(new java.awt.Color(255, 255, 255));
        labelgrade3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelgrade3.setForeground(new java.awt.Color(255, 255, 255));
        labelgrade3.setText("NOTA 3 :");

        labelaverage.setBackground(new java.awt.Color(255, 255, 255));
        labelaverage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelaverage.setForeground(new java.awt.Color(255, 255, 255));
        labelaverage.setText("AVERAGE :");

        labelstate.setBackground(new java.awt.Color(255, 255, 255));
        labelstate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelstate.setForeground(new java.awt.Color(255, 255, 255));
        labelstate.setText("ESTADO :");

        calculate.setBackground(new java.awt.Color(0, 153, 0));
        calculate.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        calculate.setForeground(new java.awt.Color(255, 255, 255));
        calculate.setText("CALCULAR");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(153, 0, 0));
        exit.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("SALIR");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        txtgrade1.setBackground(new java.awt.Color(255, 255, 255));
        txtgrade1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtgrade1.setForeground(new java.awt.Color(0, 0, 0));
        txtgrade1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrade1ActionPerformed(evt);
            }
        });
        txtgrade1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrade1KeyTyped(evt);
            }
        });

        txtgrade2.setBackground(new java.awt.Color(255, 255, 255));
        txtgrade2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtgrade2.setForeground(new java.awt.Color(0, 0, 0));
        txtgrade2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgrade2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrade2KeyTyped(evt);
            }
        });

        txtgrade3.setBackground(new java.awt.Color(255, 255, 255));
        txtgrade3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtgrade3.setForeground(new java.awt.Color(0, 0, 0));
        txtgrade3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgrade3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrade3KeyTyped(evt);
            }
        });

        txtaverage.setBackground(new java.awt.Color(255, 255, 255));
        txtaverage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtaverage.setForeground(new java.awt.Color(0, 0, 0));
        txtaverage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaverageActionPerformed(evt);
            }
        });
        txtaverage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaverageKeyTyped(evt);
            }
        });

        txtstate.setBackground(new java.awt.Color(255, 255, 255));
        txtstate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtstate.setForeground(new java.awt.Color(0, 0, 0));
        txtstate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 153, 153));
        clear.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("LIMPIAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AVERAGE");

        btnbackavg.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnbackavg.setText("ATRAS");
        btnbackavg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackavgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout averagepanelLayout = new javax.swing.GroupLayout(averagepanel);
        averagepanel.setLayout(averagepanelLayout);
        averagepanelLayout.setHorizontalGroup(
            averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(averagepanelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(averagepanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addComponent(labelgrade2)
                        .addGap(18, 18, 18)
                        .addComponent(txtgrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addComponent(labelgrade3)
                        .addGap(18, 18, 18)
                        .addComponent(txtgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addComponent(labelgrade1)
                        .addGap(18, 18, 18)
                        .addComponent(txtgrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(averagepanelLayout.createSequentialGroup()
                                .addComponent(labelaverage)
                                .addGap(18, 18, 18)
                                .addComponent(txtaverage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(averagepanelLayout.createSequentialGroup()
                                .addComponent(labelstate)
                                .addGap(18, 18, 18)
                                .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculate)
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(clear))
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnbackavg)
                            .addComponent(exit))))
                .addGap(82, 82, 82))
        );
        averagepanelLayout.setVerticalGroup(
            averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(averagepanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelgrade1)
                            .addComponent(txtgrade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelgrade2)
                            .addComponent(txtgrade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelgrade3)
                            .addComponent(txtgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(averagepanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(clear)
                        .addGap(38, 38, 38)
                        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(exit)))
                .addGap(16, 16, 16)
                .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelaverage)
                    .addComponent(txtaverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(averagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelstate)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbackavg))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(averagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(averagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrade1ActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        try
    {
        float average, suma, grade1, grade2, grade3;
        grade1 = Float.parseFloat(txtgrade1.getText());
        grade2 = Float.parseFloat(txtgrade2.getText());
        grade3 = Float.parseFloat(txtgrade3.getText());
        
        
        if ((grade1 < 0 || grade1 > 20) || (grade2 < 0 || grade2 > 20) || (grade3 < 0 || grade3 > 20)) {
            JOptionPane.showMessageDialog(null, "Notas deben ser entre 0 y 20.");
            txtgrade1.setText("");
            txtgrade2.setText("");
            txtgrade3.setText("");
            txtaverage.setText("");
            txtstate.setText("");
            return;
        }
        
        suma = grade1 + grade2 + grade3;
        
        average = ((suma) / 3);
        
        txtaverage.setText(String.valueOf(average));
        
        if (average >= 0 && average <= 9.45)
        {
            txtstate.setText(String.valueOf("REPROBADO"));
            txtstate.setForeground(Color.RED);
            txtstate.setEditable(false);
            txtaverage.setEditable(false);
        }
        else
        {
            txtstate.setText(String.valueOf("APROBADO"));
            txtstate.setForeground(Color.GREEN);
            txtstate.setEditable(false);
            txtaverage.setEditable(false);
        }
        
    }
        catch(NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "Por favor ingresa solo valores numericos validos.");
            txtgrade1.setText("");
            txtgrade2.setText("");
            txtgrade3.setText("");
        }
        
    }//GEN-LAST:event_calculateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por usar mi programa, hasta luego!");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txtgrade1.setText("");
        txtgrade2.setText("");
        txtgrade3.setText("");
        txtaverage.setText("");
        txtstate.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void txtaverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaverageActionPerformed
        // TODO add your handling code here:
        txtaverage.setEditable(false);
    }//GEN-LAST:event_txtaverageActionPerformed

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
        txtstate.setEditable(false);
    }//GEN-LAST:event_txtstateActionPerformed

    private void txtgrade1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrade1KeyTyped
        // TODO add your handling code here:
        if (txtgrade1.getText().length() >= 2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtgrade1KeyTyped

    private void txtgrade2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrade2KeyTyped
        // TODO add your handling code here:
        if (txtgrade2.getText().length() >= 2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtgrade2KeyTyped

    private void txtgrade3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrade3KeyTyped
        // TODO add your handling code here:
        if (txtgrade3.getText().length() >= 2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtgrade3KeyTyped

    private void btnbackavgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackavgActionPerformed
        // TODO add your handling code here:
        welcome frm = new welcome();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackavgActionPerformed

    private void txtaverageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaverageKeyTyped
        // TODO add your handling code here:
        if (txtaverage.getText().length() >= 5)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtaverageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new average().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel averagepanel;
    private javax.swing.JButton btnbackavg;
    private javax.swing.JButton calculate;
    private javax.swing.JButton clear;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelaverage;
    private javax.swing.JLabel labelgrade1;
    private javax.swing.JLabel labelgrade2;
    private javax.swing.JLabel labelgrade3;
    private javax.swing.JLabel labelstate;
    private javax.swing.JTextField txtaverage;
    private javax.swing.JTextField txtgrade1;
    private javax.swing.JTextField txtgrade2;
    private javax.swing.JTextField txtgrade3;
    private javax.swing.JTextField txtstate;
    // End of variables declaration//GEN-END:variables

    private static class mainpanel1 {

        public mainpanel1() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
