/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FJFF
 */
public class database extends javax.swing.JFrame {
    DefaultTableModel Model = new DefaultTableModel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(database.class.getName());

    /**
     * Creates new form database
     */
    public database() {
        initComponents();
        this.setLocationRelativeTo(null);
    
        Model.addColumn("CODIGO");
        Model.addColumn("NOMBRE");
        Model.addColumn("APELLIDO");
        Model.addColumn("SEXO");
        this.dbtable.setModel(Model);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databasepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbtable = new javax.swing.JTable();
        labelcode = new javax.swing.JLabel();
        labelname = new javax.swing.JLabel();
        labellastname = new javax.swing.JLabel();
        labelgender = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btnalldelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        txtcode = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        cbgender = new javax.swing.JComboBox<>();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        databasepanel.setBackground(new java.awt.Color(0, 51, 153));

        dbtable.setBackground(new java.awt.Color(255, 255, 255));
        dbtable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dbtable.setForeground(new java.awt.Color(0, 0, 0));
        dbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "APELLIDO", "SEXO"
            }
        ));
        dbtable.setSelectionBackground(new java.awt.Color(51, 153, 255));
        dbtable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(dbtable);

        labelcode.setForeground(new java.awt.Color(255, 255, 255));
        labelcode.setText("CODIGO :");

        labelname.setForeground(new java.awt.Color(255, 255, 255));
        labelname.setText("NOMBRE :");

        labellastname.setForeground(new java.awt.Color(255, 255, 255));
        labellastname.setText("APELLIDO :");

        labelgender.setForeground(new java.awt.Color(255, 255, 255));
        labelgender.setText("SEXO :");

        btnadd.setText("AGREGAR");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setText("ELIMINAR");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnback.setText("ATRAS");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnnew.setText("NUEVO");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnalldelete.setText("ELIMINAR TODO");
        btnalldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalldeleteActionPerformed(evt);
            }
        });

        btnexit.setText("SALIR");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        txtcode.setBackground(new java.awt.Color(255, 255, 255));
        txtcode.setForeground(new java.awt.Color(0, 0, 0));
        txtcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodeActionPerformed(evt);
            }
        });

        txtname.setBackground(new java.awt.Color(255, 255, 255));
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtlastname.setBackground(new java.awt.Color(255, 255, 255));
        txtlastname.setForeground(new java.awt.Color(0, 0, 0));
        txtlastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbgender.setBackground(new java.awt.Color(255, 255, 255));
        cbgender.setForeground(new java.awt.Color(0, 0, 0));
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "FEMENINO", "MASCULINO" }));
        cbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgenderActionPerformed(evt);
            }
        });

        btnclear.setText("LIMPIAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout databasepanelLayout = new javax.swing.GroupLayout(databasepanel);
        databasepanel.setLayout(databasepanelLayout);
        databasepanelLayout.setHorizontalGroup(
            databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(databasepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasepanelLayout.createSequentialGroup()
                        .addComponent(labellastname)
                        .addGap(18, 18, 18))
                    .addGroup(databasepanelLayout.createSequentialGroup()
                        .addComponent(labelcode)
                        .addGap(15, 15, 15)))
                .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtcode, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addComponent(txtlastname))
                    .addComponent(btnadd))
                .addGap(18, 18, 18)
                .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(databasepanelLayout.createSequentialGroup()
                        .addComponent(btnnew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnback))
                    .addGroup(databasepanelLayout.createSequentialGroup()
                        .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelname)
                            .addComponent(labelgender))
                        .addGap(22, 22, 22)
                        .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtname)
                            .addComponent(cbgender, 0, 111, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclear)
                    .addComponent(btnexit))
                .addGap(73, 73, 73))
            .addGroup(databasepanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btndelete)
                .addGap(18, 18, 18)
                .addComponent(btnalldelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        databasepanelLayout.setVerticalGroup(
            databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasepanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcode)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(databasepanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelgender)
                            .addComponent(labellastname)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(btnnew)
                            .addComponent(btnexit)
                            .addComponent(btnback))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete)
                            .addComponent(btnalldelete))
                        .addContainerGap())
                    .addGroup(databasepanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(databasepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(databasepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String[] add = new String[4];
        add[0] = txtcode.getText();
        add[1] = txtname.getText();
        add[2] = txtlastname.getText();
        add[3] = cbgender.getSelectedItem() != null ? cbgender.getSelectedItem().toString() : "";
        Model.addRow(add);
        

    }//GEN-LAST:event_btnaddActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por usar mi programa, hasta luego!");
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void cbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgenderActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int f = dbtable.getSelectedRow();
        
        if(f >= 0 )
        {
            Model.removeRow(f);
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar.");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        txtcode.setText("");
        txtname.setText("");
        txtlastname.setText("");
        cbgender.setSelectedItem(null);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnalldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalldeleteActionPerformed
        // TODO add your handling code here:
        int ftotal = dbtable.getRowCount();
        
            for(int i = ftotal - 1 ; i >= 0 ; i--)
            {
                Model.removeRow(0);
            }
        
    }//GEN-LAST:event_btnalldeleteActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
            welcome frm = new welcome();
            frm.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtcode.setText("");
        txtname.setText("");
        txtlastname.setText("");
        cbgender.setSelectedItem(null);
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new database().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnalldelete;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnew;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JPanel databasepanel;
    private javax.swing.JTable dbtable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcode;
    private javax.swing.JLabel labelgender;
    private javax.swing.JLabel labellastname;
    private javax.swing.JLabel labelname;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

  

    
}
