/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import javax.swing.JOptionPane;

/**
 *
 * @author FJFF
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel1 = new javax.swing.JPanel();
        loginlabel1 = new javax.swing.JLabel();
        userlabel1 = new javax.swing.JLabel();
        passwordlabel1 = new javax.swing.JLabel();
        enterbtn1 = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        txtpwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainpanel1.setBackground(new java.awt.Color(0, 51, 153));

        loginlabel1.setBackground(new java.awt.Color(255, 255, 255));
        loginlabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        loginlabel1.setForeground(new java.awt.Color(255, 255, 255));
        loginlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel1.setText("LOGIN");

        userlabel1.setBackground(new java.awt.Color(255, 255, 255));
        userlabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userlabel1.setForeground(new java.awt.Color(255, 255, 255));
        userlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userlabel1.setText("USUARIO");

        passwordlabel1.setBackground(new java.awt.Color(255, 255, 255));
        passwordlabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordlabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordlabel1.setText("CLAVE");

        enterbtn1.setBackground(new java.awt.Color(0, 153, 0));
        enterbtn1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        enterbtn1.setForeground(new java.awt.Color(255, 255, 255));
        enterbtn1.setText("ENTRAR");
        enterbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbtn1ActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(0, 153, 153));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("LIMPIAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(153, 0, 0));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("SALIR");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        txtuser.setBackground(new java.awt.Color(255, 255, 255));
        txtuser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(0, 0, 0));
        txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuserKeyTyped(evt);
            }
        });

        txtpwd.setBackground(new java.awt.Color(255, 255, 255));
        txtpwd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpwd.setForeground(new java.awt.Color(0, 0, 0));
        txtpwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwdActionPerformed(evt);
            }
        });
        txtpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpwdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout mainpanel1Layout = new javax.swing.GroupLayout(mainpanel1);
        mainpanel1.setLayout(mainpanel1Layout);
        mainpanel1Layout.setHorizontalGroup(
            mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainpanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanel1Layout.createSequentialGroup()
                        .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainpanel1Layout.createSequentialGroup()
                                .addComponent(txtpwd, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addGap(128, 128, 128))
                            .addGroup(mainpanel1Layout.createSequentialGroup()
                                .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainpanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(userlabel1))
                                    .addGroup(mainpanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(passwordlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(enterbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addGap(122, 122, 122))
                    .addGroup(mainpanel1Layout.createSequentialGroup()
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainpanel1Layout.setVerticalGroup(
            mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginlabel1)
                .addGap(81, 81, 81)
                .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlabel1)
                    .addComponent(enterbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordlabel1)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainpanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbtn1ActionPerformed
        String user = txtuser.getText();
        String password = txtpwd.getText();

        if(user.equals("franger") && (password.equals("29931566")))
        {
            JOptionPane.showMessageDialog(null, "Datos correctos!");
            welcome frm = new welcome();
            frm.setVisible(true);
            this.dispose();

        }

        else
        {
            JOptionPane.showMessageDialog(null, "Usuario o clave incorrectos");
            txtuser.setText("");
            txtpwd.setText("");
        }

    }//GEN-LAST:event_enterbtn1ActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        txtuser.setText("");
        txtpwd.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias por usar mi programa, hasta luego!");
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwdActionPerformed

    private void txtuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyTyped
        // TODO add your handling code here:
        if (txtuser.getText().length() >= 10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtuserKeyTyped

    private void txtpwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpwdKeyTyped
        // TODO add your handling code here:
        if (txtpwd.getText().length() >= 10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtpwdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton enterbtn1;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel loginlabel1;
    private javax.swing.JPanel mainpanel1;
    private javax.swing.JLabel passwordlabel1;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel userlabel1;
    // End of variables declaration//GEN-END:variables
}
